-spring.application.name=LibraryManagement
spring.datasource.url= jdbc:mysql://localhost:3306/Library_Management_DB?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
 
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
//Removed twilio credentials due to git hub repository violations
//twilio.account.sid=XXXXXXXXXXXXXXXXXXX
//twilio.auth.token=XXXXXXXXXXXXXXXX
//twilio.phone.number=+XXXXXXXXXX

server.address=0.0.0.0



